DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS operations_types;

CREATE TABLE accounts (
                          account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          document_number VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE operations_types (
                                  operation_type_id INT PRIMARY KEY,
                                  description VARCHAR(50) NOT NULL
);

CREATE TABLE transactions (
                              transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              account_id BIGINT NOT NULL,
                              operation_type_id INT NOT NULL,
                              amount NUMERIC(15,2) NOT NULL,
                              event_date TIMESTAMP WITH TIME ZONE NOT NULL,
                              CONSTRAINT fk_transactions_account
                                  FOREIGN KEY (account_id) REFERENCES accounts(account_id),
                              CONSTRAINT fk_transactions_operation
                                  FOREIGN KEY (operation_type_id) REFERENCES operations_types(operation_type_id)
);

